# 敏感关键词库
# 支持完全匹配和部分匹配

# 人员相关
personnel:
  - 员工名单
  - 人员信息
  - 员工编号
  - 工号
  - 劳动合同
  - 薪资表
  - 工资单
  - 花名册

# 财务相关
financial:
  - 财务报表
  - 资产负债表
  - 利润表
  - 现金流量表
  - 营业额
  - 净利润
  - 成本核算
  - 预算
  - 银行账号
  - 对公账户

# 战略规划
strategy:
  - 战略规划
  - 商业计划
  - 市场策略
  - 竞争分析
  - 产品路线图
  - 未发布产品
  - 内部文件
  - 机密
  - 保密协议
  - NDA

# 技术相关
technical:
  - API密钥
  - access key
  - secret key
  - private key
  - 私钥
  - 密码
  - token
  - 数据库连接
  - 服务器地址
  - 内网IP
  - 生产环境

# 客户相关
customer:
  - 客户名单
  - 客户信息
  - 合同金额
  - 签约客户
  - 客户数据
  - 用户数据
